# ARCHISHA SINHA

##Obtain twiddle factor matrix

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Discrete Fourier Transform

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def twiddle_matrix():
  N=int(input("Enter value of N: "))
  twiddle_matrix1=np.zeros((N,N),dtype=complex)
  for n in range(N):
    for k in range(N):
      x=int(round(np.cos(2 * np.pi * (k * n / N))))
      y=int(round(-1*(np.sin(2 * np.pi * (k * n / N)))))
      twiddle_matrix1[n,k]=complex(x,y)
  return twiddle_matrix1

In [4]:
twiddle_matrix()

Enter value of N: 8


array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
         1.+0.j],
       [ 1.+0.j,  1.-1.j,  0.-1.j, -1.-1.j, -1.+0.j, -1.+1.j,  0.+1.j,
         1.+1.j],
       [ 1.+0.j,  0.-1.j, -1.+0.j,  0.+1.j,  1.+0.j,  0.-1.j, -1.+0.j,
         0.+1.j],
       [ 1.+0.j, -1.-1.j,  0.+1.j,  1.-1.j, -1.+0.j,  1.+1.j,  0.-1.j,
        -1.+1.j],
       [ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j,  1.+0.j,
        -1.+0.j],
       [ 1.+0.j, -1.+1.j,  0.-1.j,  1.+1.j, -1.+0.j,  1.-1.j,  0.+1.j,
        -1.-1.j],
       [ 1.+0.j,  0.+1.j, -1.+0.j,  0.-1.j,  1.+0.j,  0.+1.j, -1.+0.j,
         0.-1.j],
       [ 1.+0.j,  1.+1.j,  0.+1.j, -1.+1.j, -1.+0.j, -1.-1.j,  0.-1.j,
         1.-1.j]])

Inverse Discrete Fourier Transform

In [5]:
def inv_twiddle_matrix():
  N=int(input("Enter value of N: "))
  twiddle_matrix2=np.zeros((N,N),dtype=complex)
  for n in range(N):
    for k in range(N):
      x=int(round(np.cos(2 * np.pi * (k * n / N))))
      y=int(round((np.sin(2 * np.pi * (k * n / N)))))
      twiddle_matrix2[n,k]=complex(x,y)/N
  return twiddle_matrix2

In [6]:
inv_twiddle_matrix()

Enter value of N: 8


array([[ 0.125+0.j   ,  0.125+0.j   ,  0.125+0.j   ,  0.125+0.j   ,
         0.125+0.j   ,  0.125+0.j   ,  0.125+0.j   ,  0.125+0.j   ],
       [ 0.125+0.j   ,  0.125+0.125j,  0.   +0.125j, -0.125+0.125j,
        -0.125+0.j   , -0.125-0.125j,  0.   -0.125j,  0.125-0.125j],
       [ 0.125+0.j   ,  0.   +0.125j, -0.125+0.j   ,  0.   -0.125j,
         0.125+0.j   ,  0.   +0.125j, -0.125+0.j   ,  0.   -0.125j],
       [ 0.125+0.j   , -0.125+0.125j,  0.   -0.125j,  0.125+0.125j,
        -0.125+0.j   ,  0.125-0.125j,  0.   +0.125j, -0.125-0.125j],
       [ 0.125+0.j   , -0.125+0.j   ,  0.125+0.j   , -0.125+0.j   ,
         0.125+0.j   , -0.125+0.j   ,  0.125+0.j   , -0.125+0.j   ],
       [ 0.125+0.j   , -0.125-0.125j,  0.   +0.125j,  0.125-0.125j,
        -0.125+0.j   ,  0.125+0.125j,  0.   -0.125j, -0.125+0.125j],
       [ 0.125+0.j   ,  0.   -0.125j, -0.125+0.j   ,  0.   +0.125j,
         0.125+0.j   ,  0.   -0.125j, -0.125+0.j   ,  0.   +0.125j],
       [ 0.125+0.j   ,  0.125-0.125j,  0.

##To find the DFT and IDFT of  [1,2,2,1] using twiddle factor matrix.  

DFT

In [7]:
A=np.array([1,2,2,1],dtype=complex)

In [8]:
print(A)

[1.+0.j 2.+0.j 2.+0.j 1.+0.j]


In [9]:
result=np.array([0, 0, 0, 0],dtype=complex)

In [10]:
twiddle_matrix=twiddle_matrix()

Enter value of N: 8


In [11]:
for i in range(4):
    for j in range(4):
            result[i]+= (A[j] * twiddle_matrix[i][j])
print(result)

[ 6.+0.j  2.-5.j -1.-1.j  0.-1.j]


To compare:

In [12]:
X=np.fft.fft2([A])

In [13]:
print(X)

[[ 6.+0.j -1.-1.j  0.+0.j -1.+1.j]]


IDFT

In [14]:
result2 =np.array([0, 0, 0, 0],dtype=complex)

In [15]:
twiddle_matrix_idft=inv_twiddle_matrix()

Enter value of N: 8


In [16]:
B=X[0]

In [17]:
for i in range(4):
    for j in range(4):
            result2[i]+= (B[j] * twiddle_matrix_idft[i][j])
print(result2)

[0.5 +0.j  0.75-0.5j 1.  +0.j  0.75+0.j ]


To Compare:

In [18]:
np.fft.ifft2(X)

array([[1.+0.j, 2.+0.j, 2.+0.j, 1.+0.j]])